# Generated by Django 3.0.1 on 2020-01-02 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0002_auto_20200102_2045'),
        ('stadium', '0002_auto_20200102_2045'),
        ('competetion_type', '0002_auto_20200102_2045'),
        ('round', '0006_auto_20200102_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_dateTime', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('awaySide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_side_club', to='club.Club')),
                ('competetionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competetion_type.CompetetionType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_created_by_user', to=settings.AUTH_USER_MODEL)),
                ('homeSide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_side_club', to='club.Club')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Round')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stadium.Stadium')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_updated_by_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
