# Generated by Django 3.0.1 on 2020-01-02 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('price_type', '0002_auto_20200102_2045'),
        ('games', '0001_initial'),
        ('game_prices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprice',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
        migrations.AddField(
            model_name='gameprice',
            name='priceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='price_type.PriceType'),
        ),
        migrations.AddField(
            model_name='gameprice',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
