# Generated by Django 3.0.1 on 2020-01-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competetion_type', '0002_auto_20200102_2045'),
        ('round', '0003_round_competetiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='competetionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competetion_type.CompetetionType'),
        ),
    ]
