# Generated by Django 3.0.1 on 2020-01-02 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0005_auto_20200102_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round',
            old_name='competetionType',
            new_name='CompetetionType',
        ),
    ]
