# Generated by Django 3.0.1 on 2020-01-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_records', '0002_paymentrecord_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='ticketCode',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
