# Generated by Django 3.0.1 on 2020-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_records', '0003_auto_20200118_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrecord',
            name='ticketCode',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
