# Generated by Django 3.0.1 on 2020-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_records', '0004_auto_20200118_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='recipientAccountNumber',
            field=models.CharField(default='0914040792', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='phoneNumber',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
