# Generated by Django 3.0.1 on 2020-01-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetype',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
