# Generated by Django 3.0.1 on 2020-01-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20200118_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='accountNumber',
            field=models.CharField(default='0914040792', max_length=255),
            preserve_default=False,
        ),
    ]
